### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by robertrosman** [vue-cms/theme-demo#1]
Hi!

I'm interested in taking over the organization name since this project doesn't look very active. Please contact me to discuss details :)

**Comment by liuyanzhi08** [comment]
More deteail



---Original---
From: "Robert ***@***.***&gt;
Date: Mon, Jan 9, 2023 04:21 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [vue-cms/theme-demo] Is this project dead? (Issue #1)




 
Hi!
 
I'm interested in taking over the organization name since this project doesn't look very active. Please contact me to discuss details :)

**Comment by robertrosman** [comment]
Never mind, I went with another name instead. Thank for the quick response though!
